/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FilmsIndexRouteImport } from './routes/films/index'
import { Route as FilmsSlugRouteImport } from './routes/films/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/films/': typeof FilmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/films': typeof FilmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/films/$slug': typeof FilmsSlugRoute
  '/films/': typeof FilmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/services'
    | '/films/$slug'
    | '/films/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/services'
    | '/films/$slug'
    | '/films'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/services'
    | '/films/$slug'
    | '/films/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  FilmsSlugRoute: FilmsSlugRoute,
  FilmsIndexRoute: FilmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
